server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_user?useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
    # 以下配置已经在bootstrap中配置了，所以这里就不需要了
#  application:
#    name: userservice
#  cloud:
#    nacos:
#      server-addr: localhost:8848 # nacos的服务地址

#      discovery:
#        cluster-name: SH # 集群名称，这里HZ指杭州
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SS
#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka
pattern:
  name: 本地环境local