server:
  port: 10086 #服务端口
#为了做服务注册配置
spring:
  application:
    name: eureka-server #微服务名称
eureka:
  client:
    service-url:
      #eureka的地址信息，eureka本身也是一个微服务，eureka启动时也会将自己注册到eureka上，之后会有多个eureka 进行集群
      defaultZone: http://127.0.0.1:10086/eureka